#pragma once

enum PDataType {
    TIME_RAW_TIMESTAMP,
    P_TIME,
    FRAME_NUMBER,
    CAMERA_FPS,
    PUPIL_FPS,
    PUPIL_CENTER_X,
    PUPIL_CENTER_Y,
    PUPIL_MAJOR,
    PUPIL_MINOR,
    PUPIL_WIDTH,
    PUPIL_HEIGHT,
    PUPIL_DIAMETER,
    PUPIL_UNDIST_DIAMETER,
    PUPIL_PHYSICAL_DIAMETER,
    PUPIL_CONFIDENCE,
    PUPIL_OUTLINE_CONFIDENCE,
    PUPIL_CIRCUMFERENCE,
    PUPIL_RATIO,
    PUPIL_ANGLE
};
