#pragma once

/**
    @author Gabor Benyei
*/

enum PDataType {
    TIME_RAW_TIMESTAMP,
    P_TIME,
    FRAME_NUMBER,
    CAMERA_FPS,
    PUPIL_FPS, // TODO RENAME
    PUPIL_CENTER_X,
    PUPIL_CENTER_Y,
    PUPIL_MAJOR,
    PUPIL_MINOR,
    PUPIL_WIDTH,
    PUPIL_HEIGHT,
    PUPIL_DIAMETER,
    PUPIL_UNDIST_DIAMETER,
    PUPIL_PHYSICAL_DIAMETER,
    PUPIL_CONFIDENCE,
    PUPIL_OUTLINE_CONFIDENCE,
    PUPIL_CIRCUMFERENCE,
    PUPIL_RATIO,
    PUPIL_ANGLE,
    PUPIL_BRISQUE_FULL_IMAGE,
    PUPIL_BRISQUE_PD_ROI,
    //PUPIL_BRISQUE_PD_Internal,
    // TODO ADD CAMERA TEMPERATURE, TRIAL, ETC
};
